---
title: "Traffic"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(leaflet)
library(curl)
library(tidyverse)

```

```{r, include=FALSE}

req <- curl_fetch_memory("https://api.odpt.org/api/v4/odpt:Bus?odpt:operator=odpt.Operator:SeibuBus&acl:consumerKey=c1f315c808022db68eb65b5221764083a2964e2da068ecff8f944c233afe96b7")
jsonlite::prettify(rawToChar(req$content))
bus.data.json <- jsonlite::fromJSON(jsonlite::prettify(rawToChar(req$content)))

req <- curl_fetch_memory("https://api.odpt.org/api/v4/odpt:Bus?odpt:operator=odpt.Operator:SeibuBus&acl:consumerKey=c1f315c808022db68eb65b5221764083a2964e2da068ecff8f944c233afe96b7")
jsonlite::prettify(rawToChar(req$content))
busstop.data.json <- jsonlite::fromJSON(jsonlite::prettify(rawToChar(req$content)))

```



Row
-----------------------------------------------------------------------

### Number of Bus Stop {.value-box}

```{r}

valueBox(value = as.numeric(nrow(bus.data.json)), 
         caption = "Total number of Bus available", 
         #icon = "fas fa-user-md", 
         color = "skyblue")

```

### Number_Bus {.value-box}

```{r}

valueBox(value = as.numeric(nrow(busstop.data.json)), 
         caption = "Total number of Bus Stop", 
         #icon = "fas fa-user-md", 
         color = "red")

```

Row {.tabset}
-----------------------------------------------------------------------

### Seibu Bus Map


```{r}

leaflet(bus.data.json) %>% 
  addTiles() %>% 
  addMarkers(lat = ~`geo:lat`, lng = ~`geo:long`) %>% 
  addCircles(lat = busstop.data.json$`geo:lat`, lng = busstop.data.json$`geo:long`, color="red")


```

### Nishi Tokyo Bus Map

```{r, include=FALSE}

req <- curl_fetch_memory("https://api.odpt.org/api/v4/odpt:BusstopPole?odpt:operator=odpt.Operator:NishiTokyoBus&acl:consumerKey=c1f315c808022db68eb65b5221764083a2964e2da068ecff8f944c233afe96b7")
jsonlite::prettify(rawToChar(req$content))
busstop.data.json <- jsonlite::fromJSON(jsonlite::prettify(rawToChar(req$content)))

```

```{r}

leaflet(busstop.data.json) %>% 
  addTiles() %>% 
  addCircles(lat = busstop.data.json$`geo:lat`, lng = busstop.data.json$`geo:long`, color="red")

```

### Tokyu Bus Map

```{r, include=FALSE}

req <- curl_fetch_memory("https://api.odpt.org/api/v4/odpt:BusstopPole?odpt:operator=odpt.Operator:TokyuBus&acl:consumerKey=c1f315c808022db68eb65b5221764083a2964e2da068ecff8f944c233afe96b7")
jsonlite::prettify(rawToChar(req$content))
busstop.data.json <- jsonlite::fromJSON(jsonlite::prettify(rawToChar(req$content)))

```

```{r}

leaflet(busstop.data.json) %>% 
  addTiles() %>% 
  addCircles(lat = busstop.data.json$`geo:lat`, lng = busstop.data.json$`geo:long`, color="red")

```

